# Based on https://iotechonline.com/home-assistant-install-with-docker-compose/?cn-reloaded=1
version: '3.8'
services:
  homeassistant:
    container_name: hass.io
    image: "homeassistant/home-assistant:2022.9"
    volumes:
      - /ssd/home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    ports:
      - "8123:8123"
    depends_on:
      mosquitto:
        condition: service_started
#      - mariadb
      influxdb:
        condition: service_healthy

# without mariadb, SQLite for now - https://www.home-assistant.io/docs/backend/database/
#  mariadb:
#    image: linuxserver/mariadb
#    container_name: mariadb
#    restart: unless-stopped
#    environment:
#      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
#      MYSQL_DATABASE: ha_db
#      MYSQL_USER: homeassistant
#      MYSQL_PASSWORD: "${HA_MYSQL_PASSWORD}"
#      PUID: 1000
#      PGID: 1000
#    volumes:
#      - /ssd/mariadb:/config
#    ports:
#      - "3306:3306"

  influxdb:
    image: influxdb:2.4.0
    container_name: influxdb
    restart: unless-stopped
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=influxdb-admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=XXXX
      - DOCKER_INFLUXDB_INIT_ORG=db
      - DOCKER_INFLUXDB_INIT_BUCKET=home-automation
    volumes:
      - /ssd/influxdb/data:/var/lib/influxdb2
      - /ssd/influxdb/config:/etc/influxdb2
    ports:
      - 8086:8086
    healthcheck:
      test: [ "CMD", "curl", "-sI", "http://127.0.0.1:8086/ping" ]
      interval: 30s
      timeout: 1s
      retries: 24

  grafana:
    image: "grafana/grafana:9.1.6"
    container_name: grafana
    restart: unless-stopped
    user: "${PUID}:${PGID}"
    depends_on:
      influxdb:
        condition: service_healthy
    volumes:
      - "/ssd/grafana/data:/var/lib/grafana"
    ports:
      - 3000:3000

  nodered:
    container_name: node-red
    image: nodered/node-red:3.0.2
    ports:
      - "1880:1880"
    volumes:
      - /ssd/nodered:/data
    depends_on:
      - homeassistant
      - mosquitto
    environment:
      TZ: "Europe/Warsaw"
    restart: unless-stopped

  mosquitto:
    image: eclipse-mosquitto:2.0.15
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "1884:1884"
    volumes:
      - "/ssd/HomeAutomation/mosquitto/config:/mosquitto/config"
      - "/ssd/mosquitto/data:/mosquitto/data"
      - "/ssd/mosquitto/log:/mosquitto/log"
    environment:
      - TZ=Europe/Warsaw
    user: "${PUID}:${PGID}"

#  hass-configurator:
#    image: "causticlab/hass-configurator-docker:arm"
#    container_name: hass-configurator
#    restart: unless-stopped
#    ports:
#      - "3218:3218/tcp"
#    depends_on:
#      - homeassistant
#    volumes:
#      - "/ssd/HOME_AUTOMATION/configurator-config:/config"
#      - "/ssd/HOME_AUTOMATION/hass-config:/hass-config"
#    user: "${PUID}:${PGID}"

#  portainer:
#    ports:
#      - "9000:9000"
#    container_name: portainer
#    restart: unless-stopped
#    volumes:
#      - "/var/run/docker.sock:/var/run/docker.sock"
#      - "./portainer/portainer_data:/data"
#    image: portainer/portainer-ce

# UNVERIFIED IF zigbee2mqtt has good settings
# check https://www.zigbee2mqtt.io/guide/installation/02_docker.html#docker-compose
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:1.28.0
    restart: unless-stopped
    volumes:
      - /run/udev:/run/udev:ro
      - "/ssd/zigbee2mqtt/data:/app/data"
    ports:
      - 8200:8200
    environment:
      - TZ=Europe/Warsaw
    devices:
      - /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2651605-if00:/dev/ttyACM0
